__VERIFIER_assert@0@4@  if (!(cond)) {@[ ! 0]@1@7@5@0
__VERIFIER_assert@7@7@  return;@NONE@0@NONE@NONE@0
main@0@11@  unsigned int y = x;  @NONE@0@NONE@NONE@1
main@13@13@  while (x < 5) {@[x &lt; 5]@1@15@18@0
main@14@15@    y++;    @NONE@0@NONE@NONE@0
main@18@18@  if( x != y){@[x ! y]@1@20@23@0
main@19@20@	y--;@NONE@0@NONE@NONE@0
main@22@23@	y--;@NONE@0@NONE@NONE@0
main@26@26@  __VERIFIER_assert(x == y);@NONE@0@NONE@NONE@0
