input = {[dynamicAlloc] | [dynamicRelease] | [staticAlloc] | [targetFunction] | [loadFunction] | [storeFunction]};

dynamicAlloc = "[DA] ", {dynamicAllocFunction};
dynamicAllocFunction = identifier, " ", sizeArg, " ", addrArg, "\n";

dynamicRelease = "[DR] ", {dynamicReleaseFunction};
dynamicReleaseFunction = identifier, " ", addrArg, "\n";

staticAlloc = "[SA] ", {staticAllocFunction};
staticAllocFunction = identifier, " ", sizeArg, " ", addrArg, "\n";

targetFunction = "[TARGET] ", identifier;

identifier = letter, {validChar};
sizeArg = "%size=", arg;
argAddr = "%addr=", arg;

letter = "A" | "B" | "C" | "D" | "E" | "F" | "G"
       | "H" | "I" | "J" | "K" | "L" | "M" | "N"
       | "O" | "P" | "Q" | "R" | "S" | "T" | "U"
       | "V" | "W" | "X" | "Y" | "Z" | "a" | "b"
       | "c" | "d" | "e" | "f" | "g" | "h" | "i"
       | "j" | "k" | "l" | "m" | "n" | "o" | "p"
       | "q" | "r" | "s" | "t" | "u" | "v" | "w"
       | "x" | "y" | "z" ;

digit = "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" ;       
number = ["-"], digit;

validChar = [letter | digit | "_"];

arg = [{number} | argIdentifier | binOp, "(", arg, ",", arg, ")" | unaryOp, "(", arg, ")"];
argIdentifier = ["%", {digit} | "%result"];

binOp = ["MUL" | "SUB" | "ADD" | "DIV" | "AND" | "OR" | "XOR"];
unaryOp = ["PTR" | "NOT"];


(*  Examples
**  [DA] calloc %size=MUL(%0,%1) %addr=%result
**  [DR] free   %addr=%0

*)