# Generated by CMake 3.5.2

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget stp stp_simple libstp)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target stp
add_executable(stp IMPORTED)

# Create imported target stp_simple
add_executable(stp_simple IMPORTED)

# Create imported target libstp
add_library(libstp STATIC IMPORTED)

# Import target "stp" for configuration "Release"
set_property(TARGET stp APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(stp PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/map2check/devel_tool/map_src_on_docker/dependencies/stp/stp-2.1.2"
  )

# Import target "stp_simple" for configuration "Release"
set_property(TARGET stp_simple APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(stp_simple PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/map2check/devel_tool/map_src_on_docker/dependencies/stp/stp_simple"
  )

# Import target "libstp" for configuration "Release"
set_property(TARGET libstp APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(libstp PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C;CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "/usr/lib/x86_64-linux-gnu/libboost_program_options.a;/home/map2check/devel_tool/map_src_on_docker/release/lib/libminisat.a"
  IMPORTED_LOCATION_RELEASE "/home/map2check/devel_tool/map_src_on_docker/dependencies/stp/lib/libstp.a"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
