set(REGRESSION_TYPE "TARGET")
list(APPEND MAP2CHECK_REGRESSION_${REGRESSION_TYPE} "data_structures_set_multi_proc_false-unreach-call_ground.i")
list(APPEND MAP2CHECK_REGRESSION_${REGRESSION_TYPE} "sorting_selectionsort_false-unreach-call2_ground.i")
list(APPEND MAP2CHECK_REGRESSION_${REGRESSION_TYPE} "sorting_selectionsort_false-unreach-call_ground.i")
list(APPEND MAP2CHECK_REGRESSION_${REGRESSION_TYPE} "standard_copy1_false-unreach-call_ground.i")
list(APPEND MAP2CHECK_REGRESSION_${REGRESSION_TYPE} "standard_copy2_false-unreach-call_ground.i")
list(APPEND MAP2CHECK_REGRESSION_${REGRESSION_TYPE} "standard_copy3_false-unreach-call_ground.i")
list(APPEND MAP2CHECK_REGRESSION_${REGRESSION_TYPE} "standard_copy4_false-unreach-call_ground.i")
list(APPEND MAP2CHECK_REGRESSION_${REGRESSION_TYPE} "standard_copy5_false-unreach-call_ground.i")
list(APPEND MAP2CHECK_REGRESSION_${REGRESSION_TYPE} "standard_copy6_false-unreach-call_ground.i")
list(APPEND MAP2CHECK_REGRESSION_${REGRESSION_TYPE} "standard_copy7_false-unreach-call_ground.i")
list(APPEND MAP2CHECK_REGRESSION_${REGRESSION_TYPE} "standard_copy8_false-unreach-call_ground.i")
list(APPEND MAP2CHECK_REGRESSION_${REGRESSION_TYPE} "standard_copy9_false-unreach-call_ground.i")
list(APPEND MAP2CHECK_REGRESSION_${REGRESSION_TYPE} "standard_copyInitSum2_false-unreach-call_ground.i")
list(APPEND MAP2CHECK_REGRESSION_${REGRESSION_TYPE} "standard_init1_false-unreach-call_ground.i")
list(APPEND MAP2CHECK_REGRESSION_${REGRESSION_TYPE} "standard_init2_false-unreach-call_ground.i")
list(APPEND MAP2CHECK_REGRESSION_${REGRESSION_TYPE} "standard_init3_false-unreach-call_ground.i")
list(APPEND MAP2CHECK_REGRESSION_${REGRESSION_TYPE} "standard_init4_false-unreach-call_ground.i")
list(APPEND MAP2CHECK_REGRESSION_${REGRESSION_TYPE} "standard_running_false-unreach-call.i")
list(APPEND MAP2CHECK_REGRESSION_${REGRESSION_TYPE} "standard_partition_false-unreach-call_ground.i")
list(APPEND MAP2CHECK_REGRESSION_${REGRESSION_TYPE} "standard_minInArray_false-unreach-call_ground.i")
list(APPEND MAP2CHECK_REGRESSION_${REGRESSION_TYPE} "standard_init9_false-unreach-call_ground.i")
list(APPEND MAP2CHECK_REGRESSION_${REGRESSION_TYPE} "standard_init5_false-unreach-call_ground.i")
list(APPEND MAP2CHECK_REGRESSION_${REGRESSION_TYPE} "standard_init6_false-unreach-call_ground.i")
list(APPEND MAP2CHECK_REGRESSION_${REGRESSION_TYPE} "standard_init7_false-unreach-call_ground.i")
list(APPEND MAP2CHECK_REGRESSION_${REGRESSION_TYPE} "standard_init8_false-unreach-call_ground.i")


foreach(FILE ${MAP2CHECK_REGRESSION_${REGRESSION_TYPE}})  
  set(map2check_regression_${FILE} "${SVCOMP_BASE}array-examples/${FILE}")
endforeach()

