set(REGRESSION_TYPE "OVERFLOW")
#list(APPEND MAP2CHECK_REGRESSION_${REGRESSION_TYPE} "AdditionIntMax_false-no-overflow.c.i")
list(APPEND MAP2CHECK_REGRESSION_${REGRESSION_TYPE} "AdditionIntMin_false-no-overflow.c.i")
list(APPEND MAP2CHECK_REGRESSION_${REGRESSION_TYPE} "Division_false-no-overflow.c.i")
#list(APPEND MAP2CHECK_REGRESSION_${REGRESSION_TYPE} "Multiplication_false-no-overflow.c.i")
#list(APPEND MAP2CHECK_REGRESSION_${REGRESSION_TYPE} "NoConversion_false-no-overflow.c.i")
list(APPEND MAP2CHECK_REGRESSION_${REGRESSION_TYPE} "PostfixDecrement_false-no-overflow.c.i")
list(APPEND MAP2CHECK_REGRESSION_${REGRESSION_TYPE} "PostfixIncrement_false-no-overflow.c.i")
list(APPEND MAP2CHECK_REGRESSION_${REGRESSION_TYPE} "PrefixDecrement_false-no-overflow.c.i")
list(APPEND MAP2CHECK_REGRESSION_${REGRESSION_TYPE} "PrefixIncrement_false-no-overflow.c.i")
list(APPEND MAP2CHECK_REGRESSION_${REGRESSION_TYPE} "UnaryMinus_false-no-overflow.c.i")

foreach(FILE ${MAP2CHECK_REGRESSION_${REGRESSION_TYPE}})  
  set(map2check_regression_${FILE} "${SVCOMP_BASE}signedintegeroverflow-regression/${FILE}")
endforeach()
