cmake_minimum_required(VERSION 3.5)
include(ExternalProject)
find_package(Git REQUIRED)

set(CMAKE_C_COMPILER ${CLANG_CC})
set(CMAKE_CXX_COMPILER  ${CLANG_CXX})
ExternalProject_Add( Klee
  PREFIX dependencies/Klee
  DEPENDS STP KleeUCLibC
  GIT_REPOSITORY https://github.com/klee/klee.git
  CMAKE_ARGS 
     -DCMAKE_INSTALL_PREFIX=${PRE_BUILT_CLANG_FOLDER}
     -DENABLE_SOLVER_STP=ON
     -DENABLE_POSIX_RUNTIME=ON
     -DENABLE_KLEE_UCLIBC=ON
     -DKLEE_UCLIBC_PATH=${KLEE_UCLIB_FOLDER}
     -DCMAKE_BUILD_TYPE=Release
     -DLLVM_CONFIG_BINARY=${LLVM_CONFIG}      
     -DENABLE_TCMALLOC=OFF
     -DENABLE_SYSTEM_TESTS=OFF 
     -DENABLE_UNIT_TESTS=OFF
     -DCMAKE_INSTALL_PREFIX:PATH=<INSTALL_DIR>
)

